1) public static void main(String[] args) 
  throws IOException, InterruptedException {

- throws를 쓰면 호출한 메소드가 
  IOException을 처리(예외 객체 처리)한다고 되어있는데 
  main에서 사용할 경우는 어떻게 되는건가요?
  (현재 코드에서는 try catch문을 따로 사용 안했는데,
   그렇다면 이 코드에서는 예외가 발생하면 그냥 종료되는 건가요?)
   
   
2) OutputStream out = sock.getOutputStream();
   PrintWriter writer = new PrintWriter(out, true);
   writer.println(new Date().toString());


- 여기서 out에 출력할 객체를 생성하는 것이고,
  writer의 의미를 잘 이해 못하겠습니다.
  
